# Generated by Django 2.1 on 2019-09-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190919_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checked_out',
        ),
    ]
