# Generated by Django 2.2.5 on 2019-09-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190916_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
