# Generated by Django 2.1 on 2019-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='miles',
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
